### ISSUE TITLE
Problem first time opening game1

### ISSUE THREAD

**Issue by LabusR** [romanov/monogame-fsharp#1]
Hello,

I downloaded and copied your files. I installed Visual F# Power Tools to my Visual Studio 2015 and enabled Folder Organization.
But I don't know how to check the references or what exactly to check there. Once I open the project I get the following error:

type _Game1_ () as x =

Error: The type 'ApplicationExecutionState' is required here and is unavailable. You must add a reference to assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'. 

Please help me with fixing this, for you I guess trivial, issue.
Best regards,
Robert L.

**Comment by romanov** [comment]
Hello,
check the installation or install https://www.microsoft.com/en-us/download/details.aspx?id=48179

or via VS2015 installer 
![fsharp](https://cloud.githubusercontent.com/assets/644179/19006637/592aae4a-8769-11e6-938c-29ba1c15ad59.png)

**Comment by LabusR** [comment]
Thank you mr Romanov,

I did a full new installation on my home pc and everything runs fine.
Unfortunately I cannot check on the other pc, which i got for a practical, whether the problem there could be solved by this. I´m not allowed to change anything until the practical course is other.

Thanks for your help!
